export enum Position {
    Simple = 0,
    Marksman = 1,
    GrenadeLauncher = 2,
    Medic = 3,
    Negev = 4,
    Hamal = 5,
    Sniper = 6,
    Translator = 7,
    ShootingInstructor = 8,
    KravMagaInstructor = 9,
    DroneOperator = 10,
    PlatoonCommanderComms = 11,
    CompanyCommanderComms = 12,
    ClassCommander = 13,
    Sergant = 14,
    PlatoonCommander = 15,
    CompanyDeputy = 16,
    CompanyCommander = 17
}